services:
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "5001:5001"
    # environment:
    #   - SQLD_NODE=primary
    volumes:
      - ./data/libsql:/var/lib/sqld

  sismas:
    build:
      context: .
      target: nginx-server
    image: davidaristi/sismas:devV1.0
    ports:
      - "4200:80"
    restart: always
    depends_on:
      - wiki

  wiki:
    build:
      context: .
      target: wiki
    environment:
      - ASTRO_DB_REMOTE_URL=http://db:8080
    depends_on:
      - db
    ports:
      - "4321:4321"
    restart: always
