server {
    listen 80;
    server_name localhost;

    # Proyecto Angular
    location / {
        root /web/angular;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proyecto React (Wiki)
    location /wiki {
        alias /web/wiki;
        index index.html;
        try_files $uri $uri/ /wiki/index.html;
    }
}