export interface IcaResponse {
  prIcaId:                 number;
  fechaEdicion:            Date;
  baunitId:                string;
  cadastralNumber:         string;
  prediador:               string | null;
  accion:                  string | null;
  npnFormat:               string;
  domIndividualType:       string;
  domIndividualTypeNumber: string;
  documentoIdentidad:      string;
  primerNombre:            string;
  segundoNombre:           string | null;
  primerApellido:          string;
  segundoApellido:         string | null;
  departamento:            string;
  municipio:               string;
  direccionResidencia:     string | null;
  nombreEstablecimiento:   string;
  domicilioNotificacion:   string | null;
  telefono:                string | null;
  email:                   string | null;
  notificacionElectronica: string | null;
  escritura:               string | null;
  ciudadCamara:            string | null;
  matricula:               string | null;
  fechaMatricula:          Date | null;
  fechaInicioActividades:  Date | null;
  regimenTributario:       string | null;
  estadoRegistroMercantil: string | null;
  granContribuyente:       string | null;
  domActividadPrincipal:   string | null;
  domActividadSecundaria:  string | null;
  inscritoCc:              string | null;
  foto1:                   string | null;
  foto2:                   string | null;
  foto3:                   string | null;
  foto4:                   string | null;
  foto5:                   string | null;
}
