export const environment = {
  production: true,
  url: 'https://prediosplus.api.cadastre4world.com',
  url_viewer: 'https://prediosplus.map.cadastre4world.com:8081/mapstore/',
  post_path_viewer:'rest/config/setParams',
  query_parameters_page:'../../#/context/prediosplus/11/',
  port: '5002',
  apiUrlToken:'/token/authenticate',
  ulr_icon_base:'assets/img/icons/cadastral-logos/128x128/',
  schemas: {
    main: 'main',
    temp: 'temp',
    hist: 'hist'
  },
  accessGeo:{
    value:'/accessGeo/',
    area:'area',
    extentByCodigo:'extentByCodigo',
    extentByCodigoData:'extentByCodigoData'
  },
  baunit:'/baunit/',
  baunit_npnlike: '/baunit/npnlike',
  baunit_attributes: '/baunit/attributes/',
  baunit_attributes_registration: 'matricula',
  baunit_attributes_document: 'individualNumber',
  baunit_attributes_name: 'individualName',
  baunit_attributes_address: 'direccion',
  baUnitZona_baunitId:'/baUnitZona/baunitId',
  ccDireccion:'/ccDireccion/',
  calificationUB:'/calificationUB',
  basicAddress:'/ccDireccion/baunitText',
  bpmOperation:{
    value: '/bpmOperation/',
    proflow: 'proflow/',
    proflow_proExecution: 'proflow/proExecution/',
    proExecution: 'proExecution/',
    proExecution_prev: 'proExecution/prev/',
    proExecution_next: 'proExecution/next/',
    proTask:'proTask/',
    proTask_asigned:'proTask/asigned',
    proTask_devolution:'proTask/devolutions',
    proTask_priority:'proTask/priority',
    proTask_count:'proTask/count',
    comment:'comment/',
    count: '/count'
  },
  bpmAttachment:{
    value: '/bpmAttachment/',
    proExecution:'proExecution/',
    count:'/count'
  },
  domain_domainName: '/domain/name',
  unitBuild:'/unitBuild',
  unitBuilt:'/unitBuilt',
  qbaunit_ccdpto:'/qbaunit/ccdpto',
  qbaunit_ccmpio:'/qbaunit/ccmpio',
  qbaunit_cccorr:'/qbaunit/cccorr',
  qbaunit_cczona:'/qbaunit/cczona',
  qbaunit_ccsector:'/qbaunit/ccsector',
  qbaunit_cccomuna:'/qbaunit/cccomuna',
  qbaunit_ccbarrio:'/qbaunit/ccbarrio',
  qbaunit_ccmanzana:'/qbaunit/ccmanzana',
  qbaunit_ccvereda:'/qbaunit/ccvereda',
  qbaunit_npnlike:'/baunit/npnlike',
  rrright:'/rrright/',
  valuation:'/valuation/',

};
