export interface assistantData {
  id: number;
  idempresa: number;
  empresa: string;
  id_asistente: string;
  nombre: string;
  descripcion: string;
  instrucciones: string;
  instruccion_saludo_despedida : string;
  instruccion_personalidad : string;
  modelo_predeterminado: string;
  modelo_actual: number;
  cambiar_modelo: number;
  openai : number;
  anthropic : number;
  google : number;
  llama : number;
  cic : number;
  escuchar: number;
  hablar: number;
  archivos: number;
  codigo: number;
  tavily : number;
  wikipedia : number;
  pdf : number;
  bi	: number;
  video : number;
  imgurl: string;
  id_voz: number;
  status: number;
  id_modelo_voz: number;
  similarity_boost: string;
  stability: string;
  style: string;
  use_speaker_boost: string;
  optimize_streaming_latency: string;
  nombre_voz: string;
  id_eleven: string;
  ejemplo_voz: string;
  empresa_modelo: string;
}
