// import { RuralPhysicalZone } from './rural-physical-zone';
// import { UrbanPhysicalZone } from './urban-physical-zone';
import { GeoEconomicZone } from './geo-economic-zone';

export class ZoneBAUnit {
  baUnitZonaId?: number;
  baUnitZonaArea?: number;
  ccZonaHomoFisicaRu?: CcZonaHomoFisica;
  zonaHomoFisicaRuCode?: string;
  ccZonaHomoFisicaUr?: CcZonaHomoFisica;
  zonaHomoFisicaUrCode?: string;
  ccZonaHomoGeoEconomica?: GeoEconomicZone;
  zonaHomoGeoEconomicaCode?: string;
  baUnitZonaValor?: number;
  baUnitZonaAreaE?: string;
  esComun?: boolean;
  vigencia?: number;

  constructor( baunitZona: ZoneBAUnitResponse) {
    this.baUnitZonaId = baunitZona.baUnitZonaId;
    this.baUnitZonaArea = baunitZona.baUnitZonaArea;
    this.ccZonaHomoFisicaRu = baunitZona.ccZonaHomoFisicaRu;
    this.zonaHomoFisicaRuCode = baunitZona.ccZonaHomoFisicaRu?.zonaHomoFisicaRuCode;
    this.ccZonaHomoFisicaUr = baunitZona.ccZonaHomoFisicaUr;
    this.zonaHomoFisicaUrCode = baunitZona.ccZonaHomoFisicaUr?.zonaHomoFisicaUrCode;
    this.ccZonaHomoGeoEconomica = baunitZona.ccZonaHomoGeoEconomica;
    this.zonaHomoGeoEconomicaCode = baunitZona.ccZonaHomoGeoEconomica?.zonaHomoGeoEconomicaCode;
    this.baUnitZonaValor = baunitZona.baUnitZonaValor;
    this.baUnitZonaAreaE = baunitZona.baUnitZonaAreaE;
    this.esComun = baunitZona.esComun;
    this.vigencia = baunitZona.ccZonaHomoFisicaRu?.vigencia || baunitZona.ccZonaHomoFisicaUr?.vigencia || baunitZona.ccZonaHomoGeoEconomica?.vigencia;
  }

}

export interface AddZoneParameters {
  zone: ZoneBAUnit;
  baunitId: number;
  isEdit: boolean;
  propertyType: string;
  divpolLv1: string;
  divpolLv2: string;
}

export interface ZoneBAUnitResponse {
  baUnitZonaId:           number;
  baUnitZonaArea:         number;
  ccZonaHomoFisicaRu:     CcZonaHomoFisica;
  ccZonaHomoFisicaUr:     CcZonaHomoFisica;
  ccZonaHomoGeoEconomica: CcZonaHomoGeoEconomica;
  baUnitZonaValor:        number;
  esComun:                boolean;
  hash:                   string;
  createdBy:              string;
  createdAt:              Date;
  updatedBy:              string;
  updatedAt:              string;
  baUnitZonaAreaE:        string;
}

export interface CcZonaHomoFisica {
  zonaHomoFisicaUrId?:             number;
  zonaHomoFisicaRuId?:             number;
  zonaHomoFisicaUrCode?:           string;
  zonaHomoFisicaRuCode?:           string;
  domTopografiaZonaTipo:           string;
  domInfluenciaVialUrbanaTipo?:    string;
  domInfluenciaVialRuralTipo?:     string;
  domServiciosPublicosTipo:        string;
  domUsoSueloUrbanoTipo?:          string;
  domUsoSueloRuralTipo?:           string;
  domDisponibilidadAgua?:          string;
  normaUsoSuelo:                   string;
  domTipificacionConstruccionTipo: string;
  vigencia:                        number;
  cadastreChangeLog:               CadastreChangeLog;
  divpolLv1:                       string;
  divpolLv2:                       string;
}

export interface CadastreChangeLog {
  changeLogId:                      number;
  resolution:                       string;
  resolutionAt:                     Date;
  rooting:                          string;
  rootingAt:                        Date;
  validity:                         number;
  beginAt:                          Date;
  domCadastreChangeTypeDescription: string;
}

// Generated by https://quicktype.io

export interface CcZonaHomoGeoEconomica {
  zonaHomoGeoEconomicaId:   number;
  zonaHomoGeoEconomicaCode: string;
  zonaHomoGeoEconomicaObs:  string;
  vigencia:                 number;
  cadastreChangeLog:        CadastreChangeLog;
}

export interface CadastreChangeLog {
  changeLogId:                      number;
  resolution:                       string;
  resolutionAt:                     Date;
  rooting:                          string;
  rootingAt:                        Date;
  validity:                         number;
  beginAt:                          Date;
  domCadastreChangeTypeDescription: string;
}

