// This file is generated by Astro DB
declare module 'astro:db' {
	export const Articles: import("@astrojs/db/runtime").Table<
		"Articles",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Articles","primaryKey":true}},"title":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"title","collection":"Articles","primaryKey":false,"optional":false}},"slug":{"type":"text","schema":{"unique":true,"deprecated":false,"name":"slug","collection":"Articles","primaryKey":false,"optional":false}},"content":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"content","collection":"Articles","primaryKey":false,"optional":false}},"updatedAt":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"updatedAt","collection":"Articles","default":"2026-01-22T22:39:32.246Z"}},"author":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"author","collection":"Articles","primaryKey":false,"optional":true}}}
	>;
}
