export class Ticket {
    id: number;
    groupId: number;
    priorityId: number;
    stateId: number;
    organizationId: number;
    number: string;
    title: string;
    ownerId: number;
    customerId: number;
    note: string | null;
    firstResponseAt: string | null;
    firstResponseEscalationAt: string | null;
    firstResponseInMin: number | null;
    firstResponseDiffInMin: number | null;
    closeAt: string | null;
    closeEscalationAt: string | null;
    closeInMin: number | null;
    closeDiffInMin: number | null;
    updateEscalationAt: string | null;
    updateInMin: number | null;
    updateDiffInMin: number | null;
    lastCloseAt: string | null;
    lastContactAt: string | null;
    lastContactAgentAt: string | null;
    lastContactCustomerAt: string | null;
    lastOwnerUpdateAt: string | null;
    createArticleTypeId: number;
    createArticleSenderId: number;
    articleCount: number;
    escalationAt: string | null;
    pendingTime: string | null;
    type: string | null;
    timeUnit: string | null;
    preferences: Record<string, any>;
    updatedById: number;
    createdById: number;
    createdAt: string;
    updatedAt: string;
    checklistId: number | null;
    referencingChecklistIds: number[];
    articleIds: number[];
    ticketTimeAccountingIds: number[];
  
    constructor(data: Partial<Ticket>) {
      this.id = data.id || 0;
      this.groupId = data.groupId || 0;
      this.priorityId = data.priorityId || 0;
      this.stateId = data.stateId || 0;
      this.organizationId = data.organizationId || 0;
      this.number = data.number || '';
      this.title = data.title || '';
      this.ownerId = data.ownerId || 0;
      this.customerId = data.customerId || 0;
      this.note = data.note || null;
      this.firstResponseAt = data.firstResponseAt || null;
      this.firstResponseEscalationAt = data.firstResponseEscalationAt || null;
      this.firstResponseInMin = data.firstResponseInMin || null;
      this.firstResponseDiffInMin = data.firstResponseDiffInMin || null;
      this.closeAt = data.closeAt || null;
      this.closeEscalationAt = data.closeEscalationAt || null;
      this.closeInMin = data.closeInMin || null;
      this.closeDiffInMin = data.closeDiffInMin || null;
      this.updateEscalationAt = data.updateEscalationAt || null;
      this.updateInMin = data.updateInMin || null;
      this.updateDiffInMin = data.updateDiffInMin || null;
      this.lastCloseAt = data.lastCloseAt || null;
      this.lastContactAt = data.lastContactAt || null;
      this.lastContactAgentAt = data.lastContactAgentAt || null;
      this.lastContactCustomerAt = data.lastContactCustomerAt || null;
      this.lastOwnerUpdateAt = data.lastOwnerUpdateAt || null;
      this.createArticleTypeId = data.createArticleTypeId || 0;
      this.createArticleSenderId = data.createArticleSenderId || 0;
      this.articleCount = data.articleCount || 0;
      this.escalationAt = data.escalationAt || null;
      this.pendingTime = data.pendingTime || null;
      this.type = data.type || null;
      this.timeUnit = data.timeUnit || null;
      this.preferences = data.preferences || {};
      this.updatedById = data.updatedById || 0;
      this.createdById = data.createdById || 0;
      this.createdAt = data.createdAt || '';
      this.updatedAt = data.updatedAt || '';
      this.checklistId = data.checklistId || null;
      this.referencingChecklistIds = data.referencingChecklistIds || [];
      this.articleIds = data.articleIds || [];
      this.ticketTimeAccountingIds = data.ticketTimeAccountingIds || [];
    }
  }
  