name: Deploy Quindio (SSM)

on:
  workflow_dispatch:

concurrency:
  group: sismas-deploy
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::476114140163:role/GitHub-Portal-DeployRole
          aws-region: us-east-1

      - name: Deploy Quindio
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "i-05e4578276976506e" \
            --document-name "AWS-RunShellScript" \
            --parameters commands='[
              "exec > /opt/deploy_logs/quindio.txt 2>&1",
              "set -e",
              "export CI=true",
              "cd /opt/sismas-source",
              "source /home/ec2-user/.bashrc",
              "fnm install",
              "git -c safe.directory=/opt/sismas-source fetch origin main",
              "git -c safe.directory=/opt/sismas-source reset --hard origin/main",
              "git -c safe.directory=/opt/sismas-source clean -fd",
              "/usr/bin/pnpm install --frozen-lockfile",
              "/usr/bin/pnpm run build --configuration=quindio",
              "rm -rf /usr/share/nginx/quindio.sismas.com.co/*",
              "cp -r dist/* /usr/share/nginx/quindio.sismas.com.co/"
            ]' \
            --query "Command.CommandId" \
            --output text)

          aws ssm wait command-executed \
            --command-id $COMMAND_ID \
            --instance-id i-05e4578276976506e
