
name: Deploy to Quimbaya

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        default: 'quimbaya'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v22.16.0

      - name: Install dependencies
        run: npm ci

      - name: Build Angular App
        run: node --run build -- --configuration=quimbaya

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to Quimbaya
        env:
          RSYNC_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        run: |
          rsync -avz --delete --no-perms --no-owner --no-group --no-t \
          --exclude ".htaccess" \
          --rsh="sshpass -p $RSYNC_PASSWORD ssh -o StrictHostKeyChecking=no -p ${{ secrets.SFTP_PORT }}" \
          ./dist/ ${{ secrets.SFTP_USER }}@${{ secrets.SFTP_HOST }}:/var/www/quimbaya.sismas.com.co/
